name: 🔐 Pipeline DevSecOps

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pipeline:
    name: Build, Segurança e Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 📥 Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Build
        run: |
          echo "Verificando arquivos..."
          ls src/
          npm install
          echo "Build OK!"

      - name: 🔑 Secrets Scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔍 SAST - Semgrep
        run: |
          python -m pip install --upgrade pip
          python -m pip install semgrep
          semgrep scan --config auto --error src/

      - name: 📡 SCA - Trivy
        run: |
          set -e
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy fs . --format sarif --output trivy-results.sarif --severity HIGH,CRITICAL --exit-code 1

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

      - name: 📦 SCA - Grype
        run: |
          set -e
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          grype dir:. --fail-on medium

      - name: 🌐 Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: 📤 Upload para Produção
        uses: actions/upload-pages-artifact@v3
        with:
          path: './src'

      - name: 🚀 Deploy em Produção
        id: deployment
        uses: actions/deploy-pages@v4
